apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-namespace
spec:
  type: LoadBalancer
  selector:
    app: hello-world-service
  ports:
  - name: http
    port: 3000
    targetPort: 3000