apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: dextercdalogdog/hello-world-service:dev-lts-2ac2c28c97842ffe448f3f3353def372f774dcaa
        ports:
        - containerPort: 3000
